# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: frekele/ant:1.10.3-jdk8 
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

  #  working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      PROVAR_HOME: /root/project/ProvarHome
      testproject.home: /root/project/demo
      testproject.results: /root/project/demo/ANT/Results
      #ProvarSecretsPassword: $ProvarSecretsPassword
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "demo/ANT/build.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # run: echo $PROVAR_HOME $PROVAR_SF_DemoAdmin $PROVAR_SF_DemoAdmin_password        
      - run: pwd; ls
      - run: ant -version
      - run: java -version
      #- run: sudo apt-get install openjdk-8-jdk -y
      - run: ant -lib $PROVAR_HOME/ant -f demo/ANT/build.xml
      
      - store_test_results:
          path: /root/project/demo/ANT/Results